id: !!int 6104
contentType: Card
UserActions:
  cardId: !!int 6104
  hasNotifications: !!bool false
  isIsoloated: !!bool false
  maxItems: !!int 3
  pinnable: !!bool true
title: Basic Card (with test data)
name: basic-card2
CollectionModeField:
  CollectionMode: 0
MaxItemsField:
  MaxItems: 3
PriorityField:
  Priority: 5
StreamSource: null
CardComponent: basic-card2/basic-card2-card
StoreMetadataField:
  description: 
  logourl: 
CommonPart:
  Owner: !!int 2
  Container: null
  CreatedUtc: 2017-07-21T13:26:48.5296677Z
  PublishedUtc: 2017-07-25T08:48:05.5741207Z
  ModifiedUtc: 2017-07-25T08:48:05.5176187Z
  VersionCreatedUtc: 2017-07-25T08:48:05.0000000
  VersionPublishedUtc: 2017-07-25T08:48:05.0000000
  VersionModifiedUtc: 2017-07-25T08:48:05.0000000
ServicePart:
  ConnectorTypeId: !!int 0
  ConnectorName: UpdateSubscription
  ServiceName: Subscription
  Url: ~/api/adenin.GateKeeper.Subscription/UpdateSubscription
SearchContextPart:
  Query: null
  Interface: null
CommandPart:
  CommandType: None
  Command: leave, pto, annual, time off, holiday
  DefaultDate: null
  Intent: pto_status_card
AppPart:
  App: null
  Url: 
  ExtUrl: 
  Priority: !!int 0
  AppFaceId: !!int 0
  Category: orange
  Icon: now:search
  CSSClasses: null
  Enabled: !!bool false
  NewWindow: !!bool false
  UrlWithId: !!bool true
  AvailableAppFaceRecords: null
  HasPattern: !!bool false
RoleViewPermissionsPart:
  AllowedRoles:
    - Authenticated
  Audiences: []
  Mandatory: False
RecurringTaskPart:
  Schedule: '- - - - -'
  ActivityType: adenin.Now.Activities.CardTask.UpdateCard
  StartDateUtc: null
  EndDateUtc: null
  NextOccurrenceUtc: null
  Priority: !!int 5
  Status: Enabled
  NowFlag: 0
  LastExecutionUTC: null
  EnableWebHook: !!bool false
  WebHookToken: null
